### ISSUE TITLE
Cannot read with that start in uppercase

### ISSUE THREAD

**Issue by HIKORIN01** [seth-js/yomichan-es#1]
The same problem is found in the french dictionary. I have to make sure all words are lowercase or yomichan won't register them.

**Comment by seth-js** [comment]
Make sure you're using my custom version of Yomichan. It's 100% needed or the dictionary won't work. There's code written that handles different letter casing.

![all-caps](https://user-images.githubusercontent.com/83692925/216236426-62718ae6-7ce2-4d45-8ca9-d8cab55dd226.png)
