### ISSUE TITLE
English -> Portuguese Dictionary data availability check

### ISSUE THREAD

**Issue by ghost** [seth-js/yomichan-es#5]
Hey,

Sorry for bothering again,

Recently, I have been reading difficult/old books in english, and i'm coming across too many words that are unknown for me, and the fact that i need to leave the book-page to check out the pronunciation on forvo and also to a dictionary (Chat-GPT) has been bothering me a lot.

Therefore, i wanted to know if the data available on kikkei is enough to make a dictionary with the target language in Portuguese (From English to Portuguese rather than vice-versa))

**Comment by seth-js** [comment]
Sorry for the late reply. Unfortunately, wiktextract only supports English and Chinese right now.

**Comment by ghost** [comment]
Oh, i see


thanks for your response
