### ISSUE TITLE
Is there a way to capacitate yomichan to access chrome://urls?

### ISSUE THREAD

**Issue by ghost** [seth-js/yomichan-es#7]
The problem I'm running into is that I've activated the 'Extensions on chrome:// URLs' experimental flags on Chrome. However, Yomichan doesn't request permission to access those paths. Is there a way to declare it in the manifest to always access a certain address or even the chrome:// URLs?

I'm running two instances of Yomichan without a problem since they use different characters, and they cannot interfere with each other. However, I cannot access one Yomichan instance inside another one because they have no permission.

**Comment by seth-js** [comment]
I don't think it's possible. It seems it used to be possible a decade ago, but Chrome no longer allows it for security reasons. Firefox also blocks all extensions when you're on a `moz-extension://` page.

> I cannot access one Yomichan instance inside another one 

I don't see how this would be needed anyway. If you want a site that can keep Yomichan search results all on one page, you can try a [texthooker](http://learnjapanese.moe/texthooker.html) with a [clipboard inserter](https://chromewebstore.google.com/detail/clipboard-inserter/deahejllghicakhplliloeheabddjajm).

I noticed that `yomichan-es` had some parsing issues on the texthooker page, but that's been fixed for the `yomitan-es` release that I'm still testing.

**Comment by ghost** [comment]
The main objective would be to access Yomichan Japanese with the Yomichan English that you mentioned you're going to create. Sometimes, there are many uncommon words in English that I have to spend time looking up in a dictionary, rather than just utilizing Yomichan for that purpose.

Thank you for trying to help.

**Comment by seth-js** [comment]
That makes sense. I hope that the texthooker+clipboard-inserter method works out for you. I'm still making `yomitan-en` right now. I got a newer version of OALD, but I'm still trying to properly scrape out the definitions.
