### ISSUE TITLE
Feature Request! Add frequency list as a yomichan dictionary.

### ISSUE THREAD

**Issue by ghost** [seth-js/yomichan-es#8]
In this image, the frequency list is shown in the dictionary itself, not as an Anki deck. This way is just faster to figure out the frequency. It would be cool if, like in Japanese, there was a way to see the definitions directly in Yomichan!

![image](https://github.com/seth-js/yomichan-es/assets/103891807/3779e576-98fd-4fd1-9599-da5d422dcab8)

**Comment by seth-js** [comment]
I'll try adding it for the `yomitan-es` release that I'm working on.
