### ISSUE TITLE
Bug Report! Forvo Audio Server not working on Anki 23.00+.

### ISSUE THREAD

**Issue by ghost** [seth-js/yomichan-es#9]

**Comment by seth-js** [comment]
Delete the `Spanish Forvo` folder in your Anki addons directory, and re-download `Spanish.Forvo.zip` from the [Releases](https://github.com/seth-js/yomichan-es/releases/tag/v1.1) page. You can then follow the `Forvo setup` section in the repo's readme. It should be working now.
